default_rate: 200
rates:
  junior:
    junior: 125
    senior: 150
  senior:
    junior: 150
    senior: 200
  manager:
    senior: 250
    partner: 350
  partner:
    partner: 450
utilization_targets:
  junior: 0.8
  senior: 0.8
  manager: 0.75
  partner: 0.7
