default_rate: 200
rates:
  account_manager: 250
  project_manager: 250
  creative_director: 200
  designer: 200
  copywriter: 150
  producer: 150
  analyst: 150
utilization_targets:
  account_manager: 0.85
  project_manager: 0.85
  creative_director: 0.85
  designer: 0.85
  copywriter: 0.85
  producer: 0.85
  analyst: 0.85
