alpha_complexity: 0.25
beta_workstreams: 0.12
role_mix:
  account_manager: 0.15
  project_manager: 0.15
  creative_director: 0.20
  designer: 0.25
  copywriter: 0.15
  producer: 0.05
  analyst: 0.05
min_team_composition:
  project:
    account_manager: 1
    designer: 1
  retainer:
    account_manager: 1
    designer: 1
    copywriter: 1
default_project_type: project
calibration:
  ai_confidence: 0.3
  historical_confidence: 0.7
  min_similar_contracts: 1
  similarity_threshold: 0.3
  fallback_strategy: "conservative"
